### ISSUE TITLE
Move Protein Sequence from top to bottom

### ISSUE THREAD

**Issue by luna215** [luna215/molstar#13]
We want the sequence of the protein that is displaying to be towards the bottom of the screen instead of on the top.

So, basically, we need to move the component highlighted in red to the bottom of the page for now
<img width="1439" alt="Screen Shot 2022-08-20 at 7 41 35 AM" src="https://user-images.githubusercontent.com/7971405/185752120-1be55195-d083-4d8d-a456-c880bbd28c59.png">

End result of the where the protein sequence will go to get an idea:
<img width="823" alt="Screen Shot 2022-08-20 at 7 45 41 AM" src="https://user-images.githubusercontent.com/7971405/185752319-e5fb2020-5dd4-4dd9-aa6f-596fac9fd796.png">

**Comment by luna215** [comment]
@JerryJohnsonLee can you confirm the requirements for this issue?

**Comment by JerryJohnsonLee** [comment]
Yes this is the requirement.

**Comment by luna215** [comment]
Moved to new repo
