### ISSUE TITLE
Change representation for proteins and ligands

### ISSUE THREAD

**Issue by JerryJohnsonLee** [luna215/molstar#4]
We will need to change the representations for the proteins and ligands, but the default Molstar representation control panel is a little bit too complicated. So we want to hide the default control panels and design some specific combinations of representations by which the users can switch through a button. 
An example: design a button outside of main Molstar window that changes the protein to cartoon representation (green color), residues 10-20 to line representation (color by beta-factor), and the ligand to ball and stick representation (color by atom types)

**Comment by luna215** [comment]
@JerryJohnsonLee Do you have an example of this that is live? Similar to how you shared this one: https://github.com/luna215/molstar/issues/2#issuecomment-1212346709.

**Comment by JerryJohnsonLee** [comment]
We currently do not have it. But I can create a figure similar to that in #2 to show what we want it to be like. The key point is that we want to understand how to control representations through code (like what are the available options for the representations, colors, etc.) so that we can design some different views to be used in our product.

**Comment by JerryJohnsonLee** [comment]
Okay I found that some of our requirements are not directly realizable through the Mol* UI (like apply representation only to residues 10-20) so I cannot create a snapshot.  But I believe it should be possible through code.

**Comment by luna215** [comment]
@JerryJohnsonLee 

> design a button outside of main Molstar window that changes the protein to cartoon representation (green color), residues 10-20 to line representation (color by beta-factor), and the ligand to ball and stick representation (color by atom types)

Does this mean you want 2 buttons to act as presets? Let's call them `Cartoon preset` and `Ligand Preset for now. So, if a user clicks the `Cartoon preset` then either the protein structure or the ligand structure will change their views?

**Comment by luna215** [comment]
migrated to organization molstar
