### ISSUE TITLE
Create a highlight in Molstar

### ISSUE THREAD

**Issue by JerryJohnsonLee** [luna215/molstar#6]
We want to add custom highlights (and symbols) at a certain position in the Molstar window. For example, one button will show a warning symbol (will be provided as a picture) at a given position (i.e. x=5, y=3, z=8) and it follows the rotations and translations of the view. Another button shows a dotted line between (x=4,y=6,z=9) and (x=5,y=4,z=7), and in red color.

Example warning picture (it should be shown in a size comparable to an atom):
![image](https://user-images.githubusercontent.com/16594872/184248090-e8708ab9-91fa-49f8-887c-a3e6aab2f34f.png)

**Comment by luna215** [comment]
migrated to new repo
