### ISSUE TITLE
Show an isosurface in Molstar from .cube file

### ISSUE THREAD

**Issue by JerryJohnsonLee** [luna215/molstar#7]
We would like to show isosurfaces from some 3d numerical values in .cube format(an example is provided here: https://molstar-example.s3.us-west-1.amazonaws.com/dens.0.cube, and it is associated with the .xyz structure file at https://molstar-example.s3.us-west-1.amazonaws.com/dens.0.xyz).

The result would be similar to the AlphaOrbital demo (https://molstar.org/demos/alpha-orbitals/ , https://github.com/molstar/molstar/tree/master/src/examples/alpha-orbitals), with the isovalues in the range of 0-1

**Comment by luna215** [comment]
migrated to new issue
